// ─── Re-export all types from the shared package ─────────────────────────────
// This file now serves as a local barrel so existing imports like
//   import type { User } from "@/types/api"
// continue to work without changes across all pages and components.

export type {
  // Enums
  PlatformRole,
  TenantRole,
  AccountStatus,
  PaymentStatus,
  OrderStatus,
  ShipmentStatus,
  ReturnStatus,
  TodoVisibility,
  AuditAction,
  // Models
  User,
  Gender,
  TenantMembershipSummary,
  AuthResponse,
  TokenRefreshResponse,
  Tenant,
  CreateTenantAdminPayload,
  CreateTenantPayload,
  UpdateTenantPayload,
  TenantMember,
  TenantProfile,
  AddMemberPayload,
  UpdateProfilePayload,
  UpdateMemberPayload,
  MemberDetail,
  MemberIdCard,
  // Coupons & coins
  Coupon,
  CouponType,
  CouponPayload,
  CouponRedemption,
  CouponQuote,
  CoinEntry,
  // Membership freezes
  MembershipFreeze,
  FreezeStatus,
  MemberReferral,
  MemberReferralLeader,
  Shift,
  CreateShiftPayload,
  UpdateShiftPayload,
  Subscription,
  CreateSubscriptionPayload,
  UpdateSubscriptionPayload,
  Payment,
  PaymentSummary,
  CreatePaymentPayload,
  UpdatePaymentPayload,
  Product,
  AttendanceDevice,
  CreateAttendanceDevicePayload,
  UpdateAttendanceDevicePayload,
  CreateProductPayload,
  UpdateProductPayload,
  Order,
  OrderItem,
  PlaceOrderPayload,
  // Shipping, returns and refunds
  Shipment,
  ShipmentScan,
  OrderTracking,
  ReturnRequest,
  ReturnReason,
  CreateReturnPayload,
  PincodeServiceability,
  ShippingQuote,
  Warehouse,
  CreateWarehousePayload,
  UpdateWarehousePayload,
  PickupRequest,
  SchedulePickupPayload,
  Exercise,
  WorkoutPlan,
  CreateWorkoutPlanPayload,
  UpdateWorkoutPlanPayload,
  AuditLog,
  // Badges
  Badge,
  CreateBadgePayload,
  UpdateBadgePayload,
  AssignBadgePayload,
  // Settings
  WhatsAppTemplateKey,
  WhatsAppTemplate,
  TenantSettings,
  UpdateTenantSettingsPayload,
  TenantCharge,
  CreateTenantChargePayload,
  UpdateTenantChargePayload,
  TodoActor,
  Todo,
  CreateTodoPayload,
  UpdateTodoPayload,
  // Attendance
  AttendanceRecord,
  AttendanceSummary,
  MarkAttendancePayload,
  MarkAllAttendancePayload,
  // Payment gateway
  PaymentGatewayConfig,
  UpdateGatewayPayload,
  CheckoutSession,
  VerifyCheckoutPayload,
  // Public self-signup
  SignupOptions,
  SelfSignupPayload,
  SelfSignupResult,
  TenantSignupPayload,
  TenantSignupResult,
  TenantSlugCheck,
  SignupVerifyResult,
  OrderCheckoutSession,
  // Platform Billing
  PlatformPayment,
  RecordPlatformPaymentPayload,
  // Public
  PublicTenantDetail,
  PublicGymSummary,
  // API wrappers
  ErrorCode,
  ApiResponse,
  MessageResponse,
  PaginatedResponse,
  ApiError,
} from "@fitconnect/shared";
